services:
  audiobookshelf:
    container_name: audiobookshelf
    hostname: abs.khaoohs.internal
    image: ghcr.io/advplyr/audiobookshelf:latest
    restart: unless-stopped
    ports:
      - 13378:80
    environment:
      CONFIG_PATH: /config
      HOME: /config/.home
      LOG_LEVEL: info
      METADATA_PATH: /metadata
      TZ: ${TZ}
    volumes:
      # These volumes are needed to keep your library persistent
      # and allow media to be accessed by the ABS server.
      # The path to the left of the colon is the path on your computer,
      # and the path to the right of the colon is where the data is
      # available to ABS in Docker.
      # You can change these media directories or add as many as you want
      # - ./audiobooks:/audiobooks
      # - ./podcasts:/podcasts
      # The metadata directory can be stored anywhere on your computer
      # - ./metadata:/metadata
      # The config directory needs to be on the same physical machine
      # you are running ABS on
      - /opt/docker/audiobookshelf/config:/config
      - /opt/docker/audiobookshelf/config/.metadata:/metadata
      - /mnt/zpool0:/storage
    # You can use the following user directive to run the ABS
    # docker container as a specific user. You will need to change
    # the UID and GID to the correct values for your user.
    #user: 1000:1000