name: jellyseer
services:
  jellyseerr:
    container_name: jellyseerr
    environment:
      LOG_LEVEL: debug
      TZ: America/New_York
    image: fallenbagel/jellyseerr:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5055
        published: "5055"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/docker/jellyseer
        target: /app/config
        bind:
          create_host_path: true
networks:
  default:
    name: jellyseer_default