services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      #- 7359:7359/udp
    volumes:
      - /opt/docker/jellyfin:/config
      - /opt/docker/jellyfin/cache:/cache
      # - /mnt/zpool0/processing/tubearchivist:/youtube 
      - type: bind
        source: /mnt/zpool0/media
        target: /media
      - type: bind
        source: /mnt/zpool0/media/tubearchivist
        target: /youtube
        read_only: true
      # Optional - extra fonts to be used during transcoding with subtitle burn-in
      #- type: bind
      #  source: /path/to/fonts
      #  target: /usr/local/share/fonts/custom
      #  read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    #environment:
    #  - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    #extra_hosts:
    #  - 'host.docker.internal:host-gateway' 
 
  
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
       - /opt/docker/jellyseer:/app/config
    restart: unless-stopped